In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/Explore-AI/Public-Data/master/Data/classification_sprint/claims_data.csv')
df.head()

,age,sex,bmi,steps,children,smoker,region,insurance_claim,claim_amount
0,19,female,27.900,3009,0,yes,southwest,yes,16884.9240
1,18,male,33.770,3008,1,no,southeast,yes,1725.5523
2,28,male,33.000,3009,3,no,southeast,no,0.0000
3,33,male,22.705,10009,0,no,northwest,no,0.0000
4,32,male,28.880,8010,0,no,northwest,yes,3866.8552

In [4]:
y = df['insurance_claim']

X = df.drop('insurance_claim', axis=1)

In [5]:
X_transformed = pd.get_dummies(X, drop_first=True)

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X_transformed, y, test_size=0.2, random_state=50)

In [8]:
from sklearn.linear_model import LogisticRegression

In [9]:
lr = LogisticRegression()

In [10]:
lr.fit(X_train, y_train)

LogisticRegression()

In [11]:
lr.intercept_[0]

-1.1261119753270678e-06

In [12]:
coeff_df = pd.DataFrame(lr.coef_.T, X_transformed.columns, columns=['Coefficient'])
coeff_df

                   Coefficient
age              -2.674690e-05
bmi              -1.715059e-05
steps            -9.661165e-03
children         -1.091721e-05
claim_amount      9.938677e-02
sex_male         -2.057983e-07
smoker_yes        1.188968e-06
region_northwest -9.551386e-07
region_southeast  6.362230e-07
region_southwest -6.313046e-07

In [13]:
pred_lr = lr.predict(X_test)